# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = http://localhost:3001

###

# GET Projects
GET {{Web_HostAddress}}/projects

###

# POST TodoItems
POST {{Web_HostAddress}}/projects
Content-Type: application/json

// CreateTodoItemCommand
{
  "Name": 1,
  "Deadline": "25/12/2027"
}

###



